# Traefik Static Configuration

# API and Dashboard
api:
  dashboard: true
  debug: true
  insecure: false

# Entry Points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        options: default

# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "rendiff"
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# Certificate Resolvers
certificatesResolvers:
  letsencrypt:
    acme:
      tlsChallenge: {}
      email: ${CERTBOT_EMAIL}
      storage: /letsencrypt/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
  letsencrypt-staging:
    acme:
      tlsChallenge: {}
      email: ${CERTBOT_EMAIL}
      storage: /letsencrypt/acme-staging.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory

# Global Configuration
global:
  sendAnonymousUsage: false

# Access Logs
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json

# Traefik Logs
log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"
  format: json

# Metrics
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true