global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rendiff-api'
    static_configs:
      - targets: ['api:9000']
    metrics_path: '/metrics'

  - job_name: 'krakend'
    static_configs:
      - targets: ['krakend:8090']
    metrics_path: '/__stats'
