name: CI / Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install dependencies & run tests
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
      - name: Run pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # 4. Set up Docker Buildx (for building images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5. Build Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ffmpeg-api-service:latest

      # 6. (Optional) Log in & push to GitHub Container Registry
      # To enable, add CR_PAT secret in your repo settings
      - name: Log in to GHCR
        if: secrets.CR_PAT != ''
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Push Docker image to GHCR
        if: secrets.CR_PAT != ''
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ffmpeg-api-service:latest
