# .github/workflows/ci.yml
name: CI / Test & Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies, pytest & httpx
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install pytest httpx

      - name: Export PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and load Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          load: true
          push: false
          tags: ffmpeg-api-service:latest
